import type { Metadata } from "next";
import Providers from "@/lib/providers";
import "./globals.css";
import HomeButton from "@/components/home-button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning data-lt-installed>
      <body>
        <nav className="flex my-2 items-center justify-center gap-2">
          <HomeButton href="/" />
        </nav>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
